apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.argocdNamespace }}
spec:
  project: {{ .Values.app.project }}
  source:
   - path: app
     repoURL: {{.Values.app.repoURL }}
     targetRevision: {{ .Values.app.targetRevision }}
     helm:
       valueFiles: 
         - $values/application-argocd/values.yaml
   - repoURL: {{ .Values.gitops.repoURL }}
     targetRevision: HEAD
     ref: values
  destination:
    server: {{ .Values.app.server }}
    namespace: {{ .Values.app.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.app.syncPolicy.prune }}
      selfHeal: {{ .Values.app.syncPolicy.selfHeal }}
