apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.path }}
    helm:
      valueFiles: 
        - {{ .Values.valuesFilePath }}
  destination:
    server: {{ .Values.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.prune }}
      selfHeal: {{ .Values.syncPolicy.selfHeal }}
