apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: {{ .Values.project }}
  source:
   - path: helm
     repoURL: {{.Values.repoURL }}
     targetRevision: {{ .Values.targetRevision}}
     helm:
       valueFiles: 
         - $values/application-argocd/values.yaml
   - repoURL: {{ .Values.gitops.repoURL }}
     targetRevision: HEAD
     ref: values
  destination:
    server: {{ .Values.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.prune }}
      selfHeal: {{ .Values.syncPolicy.selfHeal }}
