apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.argocdNamespace }}
spec:
  project: {{ .Values.app.project }}
  sources: 
  - repoURL: {{ .Values.chart_app.repoURL }}
    path: {{ .Values.app.path }}
    targetRevision: {{ .Values.app.targetRevision }}
    helm:
      valueFiles:
      - $values/environments/{{ .Values.global.environment }}/values.yaml
  - repoURL: {{ .Values.app.repoURL }}
    targetRevision: {{ .Values.app.targetRevision }}
    ref: values
  destination:
    server: {{ .Values.app.server }}
    namespace: {{ .Values.app.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.app.syncPolicy.prune }}
      selfHeal: {{ .Values.app.syncPolicy.selfHeal }}