apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.argocdNamespace }}
spec:
  project: {{ .Values.app.project }}
  source:
    repoURL: {{ .Values.app.repoURL }}
    targetRevision: {{ .Values.app.targetRevision }}
    path: $values/{{ .Values.app.path }}
    helm:
      valueFiles:
        - $values/environments/{{ .Values.global.environment }}/values.yaml
  destination:
    server: {{ .Values.app.server }}
    namespace: {{ .Values.app.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.app.syncPolicy.prune }}
      selfHeal: {{ .Values.app.syncPolicy.selfHeal }}
