apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OmerSade1/GitOps
    targetRevision: HEAD
    path: application-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true