app:
  name: my-app
  argocdNamespace: argocd
  project: default
  repoURL: https://github.com/OmerSade1/GitOps
  targetRevision: HEAD
  path: app
  server: https://kubernetes.default.svc
  namespace: default
  syncPolicy:
    prune: true
    selfHeal: true



replicaCount: 6



   


