app:
  name: my-app
  argocdNamespace: argocd
  project: default
  repoURL: https://github.com/OmerSade1/GitOps
  targetRevision: HEAD
  path: app
  server: https://kubernetes.default.svc
  namespace: default
  syncPolicy:
    prune: true
    selfHeal: true

chart_app: 
  repoURL: https://github.com/OmerSade1/helm-chart-app

global:
  environment: dev

replicaCount: 3



   


